# Generated by Django 5.2.17 on 2026-09-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0040_instance_public_port'),
        ('tickets', '0002_tickets_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='suppression_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TicketDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('VK', 'VK'), ('MAX', 'MAX'), ('WEB', 'Web')], max_length=32)),
                ('destination', models.CharField(max_length=255)),
                ('destination_key_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка'), ('SUPPRESSED', 'Подавлено'), ('UNCERTAIN', 'Неопределенно')], db_index=True, default='PENDING', max_length=32)),
                ('customer_notice', models.CharField(choices=[('SEND', 'Отправить'), ('SUPPRESS', 'Подавить'), ('NOT_REQUIRED', 'Не требуется')], default='SEND', max_length=32)),
                ('suppression_reason', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_error', models.TextField(blank=True, default='')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tickets.ticketevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tickets.ticket')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('event', 'destination_key_hash'), name='uniq_ticket_delivery_event_destination')
                ],
                'indexes': [
                    models.Index(fields=['status', 'lease_expires_at'], name='tickets_tic_status_ad9238_idx')
                ],
            },
        ),
    ]
