# Generated by Django 5.2.17 on 2026-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0026_message_ai_turn_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="labels",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
