# Generated by Django 5.2.17 on 2026-09-24 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_remove_channel_allow_checkout_actions_and_more'),
        ('identity', '0040_instance_public_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='routing_mode',
            field=models.CharField(choices=[('AI_FIRST', 'AI по умолчанию'), ('HUMAN_ONLY', 'Только операторы'), ('RULE_BASED', 'По правилам (гибридный)')], db_index=True, default='AI_FIRST', max_length=16),
        ),
        migrations.CreateModel(
            name='ChannelBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('weekly_schedule', models.JSONField(blank=True, default=dict)),
                ('holidays', models.JSONField(blank=True, default=list)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='channels.channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'ordering': ['channel_id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('trigger_event', models.CharField(choices=[('CONVERSATION_CREATED', 'Создание диалога'), ('MESSAGE_RECEIVED', 'Входящее сообщение')], default='CONVERSATION_CREATED', max_length=32)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action_target', models.CharField(choices=[('ROUTE_TO_AI', 'Направить агенту AI'), ('ROUTE_TO_HUMAN', 'Направить в очередь операторов'), ('ASSIGN_GROUP', 'Назначить группу операторов'), ('DROP_SILENTLY', 'Игнорировать как спам')], default='ROUTE_TO_AI', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='channels.channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='identity.organization')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.employeegroup')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['channel', 'is_active', 'priority'], name='routing_rule_channel_order')],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('priority__range', (1, 1000))),
                        name='routing_rule_priority_range',
                    ),
                ],
            },
        ),
    ]
